### PR TITLE
basic project structure

### PR DESCRIPTION
**Pull request by xdatcloud**
First version of project structure, use ocb (OpenTelemetry Builder) to organize components.

### CODE REVIEW

**Comment by fatsheep9146** [comment]
How to plan to manage the image?

**Comment by xdatcloud** [comment]
> How to plan to manage the image?

We can push image to Docker Hub by default, but for serving users on Alibaba Cloud, we should also sync images to ACS Registry, e.g. `registry.<region_id>.aliyuncs.com/acs/alibaba-otel-collector:<version_tag>`

**Comment by fatsheep9146** [comment]
> > How to plan to manage the image?
> 
> We can push image to Docker Hub by default, but for serving users on Alibaba Cloud, we should also sync images to ACS Registry, e.g. `registry.<region_id>.aliyuncs.com/acs/alibaba-otel-collector:<version_tag>`

how about adding  a issue to track this?

**Review by fatsheep9146 — APPROVED** [review]

**Comment by xdatcloud** [comment]
> > > How to plan to manage the image?
> > 
> > 
> > We can push image to Docker Hub by default, but for serving users on Alibaba Cloud, we should also sync images to ACS Registry, e.g. `registry.<region_id>.aliyuncs.com/acs/alibaba-otel-collector:<version_tag>`
> 
> how about adding a issue to track this?

Yeah, just opened an issue for tracking that: https://github.com/alibabacloud-observability/alibaba-otel-collector/issues/2

**Pull request merged**
